<?php
$user = $this->user;

$purchasesViewData  = $this->purchasesViewData;
$orderDisplayString = "";

$introPhrases=array(
'A',
'A second',
'Another',
'A fourth',
'The fifth',
'Payment six'

);

for ($i = 0, $purchaseCount = count($purchasesViewData); $i < $purchaseCount; $i++) {
	$element = $purchasesViewData[$i];
	
	$purchaseEntity  = $element['purchaseEntity'];
	$orderEntityList = $element['orderEntityList'];
	
	$orderObject = array();
	
	$list        = $orderEntityList;
	$schoolList  = array();
	$orderString = '';
	foreach ($list as $label => $element) {
		$price = number_format($element->offering->price, 2);
		$orderString .= "\n<tr><td style='padding-right:15px;'>" . $element->student->firstName . "</td>";
		$orderString .= "<td style='padding-right:15px;'>" . $element->day->title . "</td>";
		$orderString .= "<td style='padding-right:15px;'>" . $element->offering->name . "</td>";
		$orderString .= "<td>\$$price</td</tr>\n";
		
		$schoolList[$element->student->refId] = array(
			'firstName' => $element->student->firstName,
			'lastName' => $element->student->lastName,
			'school' => $element->student->school->name,
			'periodStart' => $element->student->school->datePeriodBegin,
			'periodEnd' => $element->student->school->datePeriodEnd
		);
		$merchantIdOwnerName                  = $element->student->school->merchantIdOwnerName; //by definition, all purchases in this group have the same merchantIdOwnerName
		$merchantIdOwnerName                  = $merchantIdOwnerName ? $merchantIdOwnerName : "Good Earth";
		
		$orderObject[] = array(
			'firstName' => $element->student->firstName,
			'lastName' => $element->student->lastName,
			'offering' => $element->offering->name,
			'offeringRefId' => $element->offering->refId
		);
	}
	$orderString = "<table style='margin:15px 0px 15px 20px;color:black;'>$orderString</table>\n\n";
	
	
	
	$schoolString = '';
	foreach ($schoolList as $element) {
		$schoolString .= "<div>{$element['firstName']} {$element['lastName']} at {$element['school']} school (session: {$element['periodStart']} to {$element['periodEnd']})</div>";
	}
	
	$shortRefId   = substr($purchaseEntity->refId, 0, 8);
	$showTotal    = number_format($purchaseEntity->chargeTotal, 2);
	$shortRefId   = substr($purchaseEntity->refId, 0, 8);
	$schoolString = '';
	foreach ($schoolList as $element) {
		$schoolString .= "<div>{$element['firstName']} {$element['lastName']} at {$element['school']} school (session: {$element['periodStart']} to {$element['periodEnd']})</div>";
	}
	
	$dealSubjectString = "
		{$introPhrases[$i]} payment was made to {$merchantIdOwnerName} for <span style='font-size:85%'>"."$"."{$showTotal}</span> on your credit card 
		<span style='font-size:85%'>(...{$purchaseEntity->lastFour})</span>. 
		The transaction reference number is <span style='font-size:80%'>{$purchaseEntity->fdOrderId}.
		</span> and covers the following lunches:
	";
	
	$orderDisplayString .= "
		{$dealSubjectString}
				{$orderString}
		<div>
			The lunches are for ...
			<div style='margin:15px 0px 15px 20px;font-size:10pt;'>
				{$schoolString}
			</div>
		</div>
	";
}

$extraMessage = "";


if ($purchaseCount > 1) {
	$multipleDealNotice = "
		<br/><br/>You have ordered lunches for students in separate schools, some of which collect lunch money directly. The sections below reflect separate payments that will appear on your credit card statement.
	";
}

echo "
	<body style='background:white;'><div style='color:black;font-size:12pt;margin:20px 0px 20px 10px;'>
		<div>
			Dear {$user->firstName} {$user->lastName},<p/>
				Thank you for choosing Good Earth for your child's organic school lunches! 
				We appreciate your recent purchase and the opportunity to serve you. 

				{$multipleDealNotice}<p/>
				{$orderDisplayString}
				{$extraMessage}
			
			<div style='margin:20px 0px 20px 0px;'>
				If we can be of further assistance, please let us know,
				<div style=font-weight:bold;font-style:italic;font-size:110%;'>The Good Earth Organic School Lunch Crew</div>
			</div>
			
			<div style='font-size:10pt;color:#666;margin-top:20px;'>
				The email address on this order is {$user->emailAdr}, login name is {$user->userName}
			</div>
			
			<div style='font-size:10pt;color:#008000;margin-top:20px;text-align:center;'>
				
				Good Earth School Lunch Program, 415-382-1334, school@genatural.com<br/>
				http://www.genatural.com/organic-school-lunch-program/
				
			</div>

		</div>
	</body>
	";