<?/*php require_once($_SERVER['DOCUMENT_ROOT'].'/tools/mailNotificationInclude.php');*/?>
<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN'
   'http://www.w3.org/TR/html4/strict.dtd'>
<html>
<head>
<title>Template Page Title</title>

</head>
<body>
<?php echo $this->serverComm; ?>
<div id='onlineStore' style='padding:75px;'>

<?php echo $this->layout()->content; ?>

</div>

</body>
<?php echo $this->headScript()->appendFile('/js/steal/steal.js?good_earth_store'); ?>
</html>