
modified
helixId

ALTER TABLE accounts ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE users ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE orders ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE schools ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE students ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE days ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE purchases ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE offerings ADD auditInfo MEDIUMTEXT DEFAULT NULL;
ALTER TABLE meals ADD auditInfo MEDIUMTEXT DEFAULT NULL;